### ISSUE TITLE
AuthPlugin reads the `auth` settings namespace in the pre-bind window — stored `sys_setting` rows are ignored at boot under the shipped `os serve` order

### ISSUE THREAD

**Issue by os-steve** [objectstack-ai/spec#11579]
Found by the step-1 measurement of #11045 (the settings bind-window gate). Filed per-plugin rather than fixed there, per that card's ruling: #11045 is the gate, not a fourth declaration.

## What happens

`AuthPlugin` reaches `getService('settings')` from `kernel:ready` handlers it registers in `start()`, and it uses the handle in the same tick:

- `packages/plugins/plugin-auth/src/auth-plugin.ts:1207` — `bindAuthSettings()` resolves the handle and then `await applySettings()`, which calls `settings.getNamespace('auth')`.
- `packages/plugins/plugin-auth/src/auth-plugin.ts:728` — the second acquisition in the same plugin.

It is reached transitively, at depth 3 from one of the registrations:

```
ctx.hook('kernel:ready', () => runBackfill('kernel:ready'))   // auth-plugin.ts:1029
  → runBackfill (a const inside start())
    → this.ensureAuthSettingsBound(ctx)                        // :1188
      → this.bindAuthSettings(ctx)                             // :1202
        → ctx.getService<SettingsReadSurface>('settings')      // :1207
          → await settings.getNamespace('auth')
```

and at depth 2 from `auth-plugin.ts:674`.

`SettingsServicePlugin` binds its data engine from its *own* `start()`-registered `kernel:ready` hook (`settings-service-plugin.ts:153`). Handlers run in registration order, and registration order is `start()` order. `AuthPlugin` declares `dependencies = ['com.objectstack.engine.objectql']` and nothing about settings, so nothing orders it after the settings plugin.

## Why it fires on the shipped composition

`packages/cli/src/commands/serve.ts` does `kernel.use(new AuthPlugin(...))` at line 2693; `SettingsServicePlugin` arrives later, from the capability loop at line ~3417. `resolvePluginOrder` preserves insertion order for plugins with no edge between them, so auth starts first.

Measured with the real `resolvePluginOrder` from `packages/core/src/plugin-order.ts`, fed the verbatim declarations of the five plugins involved in the `serve` insertion order:

```
start() order: ["com.objectstack.engine.objectql","com.objectstack.auth","com.objectstack.audit","com.objectstack.service.settings","com.objectstack.mcp"]
auth  before settings?  true
```

So auth's `kernel:ready` handlers are registered — and therefore fire — before the engine bind.

## Consequence

In that window `SettingsService.loadRows` takes its `this.memory` branch, so `getNamespace('auth')` answers the manifest defaults with `source: 'default'` while the deployment's persisted `sys_setting` rows go unread (this is the exact class #10250 documented and made audible via `reportPreBindRead`). Everything `applySettings()` derives is therefore computed from defaults at boot: the ADR-0093 membership policy the D6 backfill runs under, and the `google_*` social-provider config. `settings.subscribe('auth', …)` only re-applies on a *later* change, so a workspace that configured auth in Setup and never touched it again keeps booting with the wrong values.

Note the D6 backfill's own comment at `auth-plugin.ts:1175` already reasons about this ordering hazard between auth's two hooks — the hazard against the *settings plugin* is the one still open.

## Repair

The #10250 shape — one declaration on `AuthPlugin`:

```ts
optionalDependencies = ['com.objectstack.service.settings'];
```

`requiresServices` would not do it: that asserts the service is registered before `init()` (it always is), and carries no `start()` ordering.

Verification: after the fix, `pnpm check:settings-bind-window` must go green with the `com.objectstack.auth` entry **deleted** from `KNOWN_PRE_BIND_READS` in `scripts/check-settings-bind-window.mjs` — that ledger is shrink-only and errors on a stale entry, so the deletion is part of the fix, not follow-up.

Suggested lane: whoever owns `packages/plugins/plugin-auth`.

**Comment by os-zhuang** [comment]
Triage (Routine seat, hourly round): → `pm:queue` + `domain:services`, type Bug.

Rationale: lands in `packages/plugins/plugin-auth` (anchoring rule). Concrete declared≠delivered defect with a named, measured repair (#10250 shape: `optionalDependencies = ['com.objectstack.service.settings']`) and a built-in verification (`check:settings-bind-window` green with the `com.objectstack.auth` entry deleted from the shrink-only ledger). Sibling card #11580 is the same pre-bind class in `packages/mcp` — different lane, not foldable across seats.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by os-sam** [comment]
**Claimed** by the `domain:services` execution seat — PM session `session_01APWX2AwT3a4xDcjPCe8bk4`, branch `claude/issue-11579-auth-settings-prebind`. Now `pm:dispatched`.

The grading gives this card two things most cards don't have, and both are carried into the brief:

- a **named repair shape** — the #10250 pattern, `optionalDependencies = ['com.objectstack.service.settings']`
- a **built-in verification** — `check:settings-bind-window` must go green with the `com.objectstack.auth` entry deleted from the shrink-only ledger

⭐ That second one is the real acceptance test, and it is stronger than an ordinary suite pass: the gate's own ledger is the thing that has to shrink. The dev is told the deletion of that entry **is** the deliverable's proof, and that a green `check:settings-bind-window` with the entry still present proves nothing about this card.

⛔ **The ledger is shrink-only.** Removing the `com.objectstack.auth` entry because the defect is fixed is the sanctioned direction. Adding, re-adding, or otherwise weakening any entry to get green is not — that is the maintainer's call, and it is the exact forbidden shortcut two devs were stopped from taking on other ratchets earlier in this shift.

Serial note from the grading, recorded so nobody folds them: sibling card **#11580** is the same pre-bind class in `packages/mcp` — **different lane, not foldable across seats.** Do not touch `packages/mcp` here.

⛔ Fences: no `packages/spec/**`, no `content/docs/releases/**`, no governed surfaces. Spec edit needed → stop and report; the contract half splits to the spec seat.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by os-sam** [comment]
```json
{
  "issue": 11579,
  "status": "done",
  "branch": "claude/issue-11579-auth-settings-prebind",
  "pr": "https://github.com/objectstack-ai/objectstack/pull/11619",
  "premise_still_valid": true,
  "summary": "Re-measured on current main first: `check:settings-bind-window --list` still reported `undeclared  packages/plugins/plugin-auth/src/auth-plugin.ts:1207` and `:728  AuthPlugin -> getService('settings')  <ready-hook-from-start>`, and the baseline verdict still read `2 ledgered`, so the com.objectstack.auth entry was still in KNOWN_PRE_BIND_READS. Repair is the #10250 shape and nothing else: `optionalDependencies = ['com.objectstack.service.settings']` on AuthPlugin, with a doc comment stating the mechanism, the shipped-composition consequence (os serve uses AuthPlugin before the capability loop registers SettingsServicePlugin) and why it is soft rather than hard. Deleted the com.objectstack.auth entry from the shrink-only ledger; NO entry added, re-added or weakened, and the com.objectstack.mcp row (#11580) is untouched. Added packages/plugins/plugin-auth/src/auth-settings-ordering.pin.test.ts (5 cases) as the ADR-0049 half, plus a changeset. packages/mcp not touched.",
  "tests": "Union re-run AFTER the final commit, at HEAD 87d39a7e9e (branch head pushed). ACCEPTANCE, quoted from the gate's own output with the ledger entry removed: `✓ settings bind-window: 4 declared / 0 self / 1 structurally upstream / 1 ledgered (68 plugin unit(s) scanned, provider 'com.objectstack.service.settings').` — baseline was `3 declared / ... / 2 ledgered`, so auth moved from ledger to declared. POSITIVE CONTROL, measured before the fix (entry deleted, defect still standing): exit 1, `✗ settings bind-window guard (#11045)` / `packages/plugins/plugin-auth/src/auth-plugin.ts:1207 — AuthPlugin` / `1 settings read(s) in the pre-bind window with no declaration covering them.` So the green is a measurement, not a suppression. `--self-test`: `✓ settings bind-window guard self-test: all cases pass.` Suite: `pnpm --filter @objectstack/plugin-auth test` (through scripts/pm/os-verify-lock.sh) `VERDICT command-exit 0`, `Test Files 73 passed (73) · Tests 1480 passed (1480)`; the new file's participation is proved by count, not assumed — 72 tracked *.test.ts at BASE 2cf5a96cc7 vs 73 on disk vs 73 passed — and a targeted verbose run shows all 5 cases green individually. Typecheck: `VERDICT command-exit 0` after building the package's own dist (the first red was `examples/basic-usage.ts ... TS2307: Cannot find module '@objectstack/plugin-auth'`, an unbuilt-artifact fault, not this change — filed as #11620). ZERO-MARGIN RATCHET this change could have moved: TEST_DEBT['@objectstack/plugin-auth'] = 97 raw tsc errors with no margin, and the package tsconfig EXCLUDES **/*.test.ts so the green package typecheck does not cover the new file. Mirrored measureTestDebt with a temp in-package project (exclusion lifted, dependency closure built, trap restore against an absolute path, temp config verified ABSENT on disk afterwards): RAW_ERROR_LINES_TOTAL=97 (the ledger's number exactly, which is what makes the instrument credible), LINES_MENTIONING_MY_NEW_TEST_FILE=0, SETUP_ERRORS=0. Gate list derived with `node scripts/pm/dispatch-gates.mjs --repo objectstack-ai/objectstack` from the real change set (4 paths, three-dot vs merge base), not a hand-written diff. All green: check:nul-bytes, check:test-source-alias (no registry change needed), check:slot-lookup, check:query-options-erasure, check:engine-double-contract, check:where-matcher, check:type-check-coverage, check:cross-package-test-inputs, check:auth-mount-ledger, check:route-envelope, check:plugin-teardown-shape, check:published-files, check:entry-guard, check:parse-guard, check:pnpm-filter-targets, check:ci-filter-parity, check:type-source-resolution, the changeset family and docs-audit/check-affected-docs. NOT MEASURED, declared: (1) repo-wide `pnpm lint` — the shared lock had a holder plus a waiter and queuing risked the foreground cap, so a DECLARED NARROWING with its three evidence items instead: population read from eslint's own config (it reports the .changeset/*.md as 'File ignored because no matching configuration was supplied'), count from --format json (4 results, 3 linted, 0 errors 0 warnings), and invariance quoted from eslint.config.mjs's own docblock ('never enables type-aware linting ... for ANY file'), with no eslint config touched by this diff; (2) `check:type-check-debt --re-measure` whole — it refuses without the entire ledgered closure built; the one entry this change could move was measured directly, above; (3) no browser/dogfood run — the change is a declaration read by resolvePluginOrder. Exit codes were captured before any pipe throughout, and every verdict quoted here is the gate's own printed line, never a bare $?.",
  "open_questions": [],
  "out_of_scope_findings": [
    "filed as #11620: `@objectstack/plugin-auth`'s `typecheck` cannot pass unless the package's OWN dist/ is built — examples/basic-usage.ts imports the package by name (resolves through exports to dist/), while turbo's typecheck task dependsOn ['^build'] (dependencies only) and excludes dist/** from inputs. Invisible in CI, which builds first; labelled `finding`, unassigned, no pm:queue."
  ]
}
```


---
_Generated by [Claude Code](https://claude.ai/code)_
